steps:
- name: maven:3.6.0-jdk-11-slim
  entrypoint: 'mvn'
  args: ['clean', 'install', 'package', '-DskipTests']
    
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/helloworld-java-docker/helloworldwebapp', '.']
  
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/helloworld-java-docker/helloworldwebapp']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
images: ['gcr.io/$PROJECT_ID/helloworld']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=anthos-sample-cluster1'
