steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', 'package', '-DskipTests']
    
  - name: 'Building and pushing docker image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
  images: ['gcr.io/$PROJECT_ID/helloworld']
